### ISSUE TITLE
Plugin was built with a different version of package internal/cpu"

### ISSUE THREAD

**Issue by bruteforce1414** [nori-io/nori#13]
Error occured, when plugins tried to start by engine Nori. Engine built in docker container.
Docker built Nori by golang 1.13.4
Plugins was built by  golang 1.13.4 too with Makefile.
Error is "Plugin was built with a different version of package internal/cpu" for all plugins

**Comment by bruteforce1414** [comment]
What version of Go are you using (go version)?
1.13.4 in container and my os linux ubuntu 18.04

Does this issue reproduce with the latest release?
i tried only with 1.13.04

What operating system and processor architecture are you using (go env)?
ON MY OS:
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/anita/.cache/go-build"
GOENV="/home/anita/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/anita/.go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/anita/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/anita/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/anita/goprojects/src/github.com/nori-io/nori/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build280562468=/tmp/go-build -gno-record-gcc-switches"


What did you do?
start Nori engine with plugins

What did you expect to see?
Start of Engine without error "Plugin was built with a different version of package internal/cpu" for all plugins


What did you see instead?
error 
"Plugin was built with a different version of package internal/cpu" for all plugins

**Comment by cheebo** [comment]
Do you build Nori and plugin in docker or you build Nori in docker, but plugin on host system?

**Comment by bruteforce1414** [comment]
We had changed the process of compilation engine and plugins. And the error doesn't occure. Engine and plugins inside docker containers build successfully.
