### ISSUE TITLE
graph_test.go

### ISSUE THREAD

**Issue by bruteforce1414** [nori-io/nori#4]
Add information about absent interface.
In last string interface is absent. Add additi:nal information in Sort() function?
Result of test n.5:
graph_test.go:307: Plugins' order until sorting:
    graph_test.go:313: Plugin n. 1  in list until sotring: plugin1:1.0  Dependencies:
    graph_test.go:317: Dependence n. 1 for plugin1 is [:~>1.0][interface: HTTP]
    graph_test.go:323: 
    graph_test.go:326: plugin1:1.0
        Dependency [][~>1.0] not found

**Comment by cheebo** [comment]
is it actual issue?

**Comment by bruteforce1414** [comment]
no, you fixed it in May
