### ISSUE TITLE
nori-io/nori/core/plugins/dependency/manager_test.go fail

### ISSUE THREAD

**Issue by bruteforce1414** [nori-io/nori#7]
=== RUN   TestManager_Resolve
--- FAIL: TestManager_Resolve (0.00s)
panic: 
assert: mock: I don't know what to return because the method call was unexpected.
	Either do Mock.On("GetInterface").Return(...) first, or remove the GetInterface() call.
	This method was unexpected:
		GetInterface()
		
	at: [Meta.go:73 manager.go:138 manager.go:83 manager_test.go:89] [recovered]
	panic: 
assert: mock: I don't know what to return because the method call was unexpected.
	Either do Mock.On("GetInterface").Return(...) first, or remove the GetInterface() call.
	This method was unexpected:
		GetInterface()
		
	at: [Meta.go:73 manager.go:138 manager.go:83 manager_test.go:89]

**Comment by cheebo** [comment]
need to check it after core refactoring.
