### ISSUE TITLE
nori-io/nori/core/plugins/registry_manager_test.go fail

### ISSUE THREAD

**Issue by bruteforce1414** [nori-io/nori#8]
=== RUN   TestNewRegistry
--- FAIL: TestNewRegistry (0.00s)
    registry_manager_test.go:48: 
        	Error Trace:	registry_manager_test.go:48
        	Error:      	Expected value not to be nil.
        	Test:       	TestNewRegistry
FAIL

**Comment by cheebo** [comment]
is it still valid after refactoring?

**Comment by bruteforce1414** [comment]
File registry_manager_test.go and similar files were not found, and function TestNewRegistry too.
